from dataclasses import dataclass

DOMAIN = "solvis_control"

CONF_NAME = "name"
CONF_HOST = "host"
CONF_PORT = "port"

DATA_COORDINATOR = "coordinator"
MANUFACTURER = "Solvis"


@dataclass(frozen=True)
class ModbusFieldConfig:
    name: str
    address: int
    unit: str
    device_class: str
    state_class: str
    multiplier: float = 0.1
    # 1 = INPUT, 2 = HOLDING
    register: int = 1
    negative: bool = False
    absolut_value: bool = False
    entity_category: str = None
    enabled_by_default: bool = True
    edit: bool = False
    data: tuple = None


PORT = 502
REGISTERS = [
    ModbusFieldConfig(  # ZirkulationBetriebsart
        name="zirkulation_betriebsart",
        address=2049,
        unit="",
        device_class=None,
        state_class=None,
        multiplier=1,
        # data=("0", "1", "2", "3"),
    ),
    ModbusFieldConfig(  # WW Modus
        name="ww_mode",
        address=2304,
        unit="",
        register=2,
        multiplier=1,
        edit=True,
        data=(0, 32767),
        enabled_by_default=False,
    ),
    ModbusFieldConfig(  # WW Solltemperatur
        name="ww_solltemperatur",
        address=2305,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(10, 65),
    ),
    ModbusFieldConfig(  # WW Nachheizen Start
        name="ww_nachheizen_start",
        address=2328,
        unit="",
        device_class=None,
        state_class=None,
        register=2,
        multiplier=1,
        data=("0", "1"),
    ),
    ModbusFieldConfig(  # HKR1 WW Vorrang
        name="hkr1_ww_vorrang",
        address=2817,
        unit="",
        device_class=None,
        state_class=None,
        register=2,
        multiplier=1,
        data=("0", "1"),
    ),
    ModbusFieldConfig(  # HKR1 Betriebsart
        name="hkr1_betriebsart",
        address=2818,
        unit="",
        device_class=None,
        state_class=None,
        register=2,
        multiplier=1,
        data=("2", "3", "4", "5", "6", "7"),
    ),
    ModbusFieldConfig(  # HKR1 Solltemperatur Tag
        name="hkr1_solltemperatur_tag",
        address=2820,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 75),
    ),
    ModbusFieldConfig(  # HKR1 Absenktemperatur
        name="hkr1_absenktemperatur",
        address=2821,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 75),
    ),
    ModbusFieldConfig(  # HKR1 Heizkurve Tag Temperatur 1
        name="hkr1_heizkurve_tag_temperatur_1",
        address=2822,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 50),
    ),
    ModbusFieldConfig(  # HKR1 Heizkurve Tag Temperatur 2
        name="hkr1_heizkurve_tag_temperatur_2",
        address=2823,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 30),
    ),
    ModbusFieldConfig(  # HKR1 Heizkurve Tag Temperatur 3
        name="hkr1_heizkurve_tag_temperatur_3",
        address=2824,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 30),
    ),
    ModbusFieldConfig(  # HKR1 Heizkurve Absenktemperatur
        name="hkr1_heizkurve_absenktemperatur",
        address=2825,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(5, 30),
    ),
    ModbusFieldConfig(  # HKR1 Heizkurve Steilheit
        name="hkr1_heizkurve_steilheit",
        address=2832,
        unit="",
        device_class="",
        state_class="measurement",
        register=2,
        multiplier=0.1,
        edit=True,
        data=(20, 250),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub zu Hause Temperatur
        name="hkr1_urlaub_zu_hause_temperatur",
        address=2870,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=0.1,
        edit=True,
        data=(0, 30),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub zu Hause Dauer
        name="hkr1_urlaub_zu_hause_dauer",
        address=2871,
        unit="d",
        device_class="",
        state_class="",
        register=2,
        multiplier=1,
        edit=True,
        data=(0, 31),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub zu Hause Heizen Start
        name="hkr1_urlaub_zu_hause_heizen_start",
        address=2872,
        unit="h",
        device_class="",
        state_class="",
        register=2,
        multiplier=1,
        edit=True,
        data=(0, 95),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub zu Hause Heizen Stop
        name="hkr1_urlaub_zu_hause_heizen_stop",
        address=2873,
        unit="h",
        device_class="",
        state_class="",
        register=2,
        multiplier=1,
        edit=True,
        data=(0, 95),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub auswärts Temperatur
        name="hkr1_urlaub_auswaerts_temperatur",
        address=2880,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(0, 30),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub auswärts bis Tag
        name="hkr1_urlaub_auswaerts_bis_tag",
        address=2881,
        unit="d",
        device_class="",
        state_class="",
        register=2,
        multiplier=1,
        edit=True,
        data=(1, 31),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub auswärts bis Monat
        name="hkr1_urlaub_auswaerts_bis_monat",
        address=2882,
        unit="m",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(1, 12),
    ),
    ModbusFieldConfig(  # HKR1 Urlaub auswärts bis Jahr
        name="hkr1_urlaub_auswaerts_bis_jahr",
        address=2883,
        unit="y",
        device_class="temperature",
        state_class="measurement",
        register=2,
        multiplier=1,
        edit=True,
        data=(2006, 2099),
    ),


    ModbusFieldConfig(  # VersionSC3
        name="version_sc3",
        address=32770,
        unit="",
        device_class=None,
        state_class=None,
        multiplier=1,
        entity_category="diagnostic",
    ),
    ModbusFieldConfig(  # VersionNBG
        name="version_nbg",
        address=32771,
        unit="",
        device_class=None,
        state_class=None,
        multiplier=1,
        entity_category="diagnostic",
    ),
    ModbusFieldConfig(  # Warmwasserpuffer
        name="tank_layer4_water_temp",
        address=33024,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Warmwassertemperatur
        name="domestic_water_temp",
        address=33025,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Speicherreferenztemperatur
        name="tank_layer1_water_temp",
        address=33026,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Heizungspuffertemperatur oben
        name="tank_layer3_water_temp",
        address=33027,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(
        name="solar_heat_exchanger_out_water_temp",
        address=33028,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        enabled_by_default=False,
    ),
    ModbusFieldConfig(
        name="solar_heat_exchanger_in_water_temp",
        address=33029,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        enabled_by_default=False,
    ),
    ModbusFieldConfig(
        name="solar_water_temp",
        address=33030,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        enabled_by_default=False,
    ),
    ModbusFieldConfig(
        name="roof_air_temp",
        address=33031,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        enabled_by_default=False,
    ),
    ModbusFieldConfig(  # Heizungspuffertemperatur unten
        name="tank_layer2_water_temp",
        address=33032,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        negative=True,
        absolut_value=True,
    ),
    ModbusFieldConfig(  # Außentemperatur
        name="outdoor_air_temp",
        address=33033,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Zirkulationsdurchfluss
        name="cold_water_temp",
        address=33034,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        multiplier=0.1,
    ),
    ModbusFieldConfig(  # Vorlauftemperatur
        name="flow_water_temp",
        address=33035,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Kaltwassertemperatur
        name="cold_water_temperatur",
        address=33038,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
    ),
    ModbusFieldConfig(
        name="solar_water_flow",
        address=33040,
        unit="l/min",
        device_class=None,
        state_class="measurement",
        enabled_by_default=False,
    ),
    ModbusFieldConfig(  # Durchfluss Warmwasserzirkualation
        name="domestic_water_flow",
        address=33041,
        unit="l/min",
        device_class=None,
        state_class="measurement",
    ),
    ModbusFieldConfig(  # DigIn Stoerungen
        name="digin_stoerungen",
        address=33045,
        unit="",
        device_class=None,
        state_class=None,
        multiplier=1,
        entity_category="diagnostic",
    ),
    ModbusFieldConfig(  # A01.Pumpe Zirkulation
        name="a01_pumpe_zirkulation",
        address=33280,
        unit="V",
        device_class="voltage",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # A02.Pumpe Warmwasser
        name="a02_pumpe_warmwasser",
        address=33281,
        unit="V",
        device_class="voltage",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # A03.Pumpe HK1
        name="a03_pumpe_hk1",
        address=33282,
        unit="V",
        device_class="voltage",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # A05.Pumpe Zirkulation
        name="a05_pumpe_zirkulation",
        address=33284,
        unit="V",
        device_class="voltage",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # A12.Brennerstatus
        name="a12_brennerstatus",
        address=33291,
        unit="V",
        device_class="voltage",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Laufzeit Brenner
        name="runtime_gasburner",
        address=33536,
        unit="h",
        device_class="time",
        state_class="measurement",
        entity_category="diagnostic",
    ),
    ModbusFieldConfig(  # Brennerstarts
        name="number_gas_burner_start",
        address=33537,
        unit="",
        device_class="",
        state_class="measurement",
        negative=True,
        multiplier=1,
        entity_category="diagnostic",
        absolut_value=True,
    ),
    ModbusFieldConfig(  # Laufzeit Brenner 2
        name="runtime_gasburner_2",
        address=33538,
        unit="h",
        device_class="time",
        state_class="measurement",
        entity_category="diagnostic",
    ),
    ModbusFieldConfig(  # Brennerleistung
        name="gas_power",
        address=33539,
        unit="kW",
        device_class="power",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Ionisationsstrom
        name="ionisation_voltage",
        address=33540,
        unit="mA",
        device_class="ampere",
        state_class="measurement",
    ),
    ModbusFieldConfig(  # Raumtemperatur_HKR1
        name="raumtemperatur_hkr1",
        address=34304,
        unit="°C",
        device_class="temperature",
        state_class="measurement",
        register=2,
        edit=True,
        data=(0, 40),
    ),
]
